locales:
  bla:
    name: Siksika Keyboards
    description: >-
      Mobile OS keyboards for the Siksika language from the Divvun group
      at UiT.
  en:
    name: Siksika Keyboards
    description: >-
      Mobile OS keyboards for the Siksika language from the Divvun group
      at UiT.
  nb:
    name: Siksika tastatur
    description: Mobiltastatur for Siksika fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
